<?php

/**
 * Implements hook_preprocess_HOOK() for region.html.twig.
 */
function ffw_preprocess_region(&$variables) {
  if ($variables['region'] === 'header') {
    $variables['attributes']['class'][] = 'collapse navbar-collapse navbar-collapse-topmenu noprint';
  }
}

/**
 * Implements hook_preprocess_HOOK() for region.html.twig.
 */
function ffw_preprocess_menu(&$variables) {
  if ($variables['menu_name'] === 'main') {
    $variables['attributes']['class'][] = 'topmenu-list';
  }
}
